version: 2.1

executors:
  k8s-runner:
    docker:
      - image: cimg/python:3.11  # or any container image
    resource_class: mylaptop/test

jobs:
  test:
    executor: k8s-runner
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            python -m unittest discover

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
